#!/bin/sh
#
# Script that demos, command line args
#

echo "Total number of command line arguments are $#"
echo "$0 is the script name"
echo "$1 is the first argument"
echo "$2 is the second argument"
echo "All of them are :- $* or $@"

